#define SERIAL_BAUD 115200 // Serial Port Conf
#define LED D3
#define MOISTURES A0

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASS"

#define MQTT_SERVER "YOUR_MQTT_SERVER"
#define MQTT_PORT 1883
#define MQTT_USER "YOUR_MQTT_USER"
#define MQTT_PASSWORD "YOUR_MQTT_PASS"

#define BUFFER_SIZE 50

#define MQTT_TOPICHS "Topic1"
#define MQTT_TOPICH "Topic2"
#define MQTT_TOPICT "Topic3"
#define MQTT_TOPICP "Topic4"
